### ISSUE TITLE
Version and feature matching with daisy

### ISSUE THREAD

**Issue by gotjoshua** [kidonng/daisyui#1]
Do you have plans to match daisy [version by version?
](https://github.com/saadeghi/daisyui/tags)
Is your code base auto generated from daisy or is there much manual effort needed?

Thanks very much for the contribution!

**Comment by kidonng** [comment]
> Do you have plans to match daisy [version by version?](https://github.com/saadeghi/daisyui/tags)

Good question. There are still a couple of pending changes before I can claim this "done", then we may try something like automated updates.

> Is your code base auto generated from daisy or is there much manual effort needed?

It's generated by [`build.ts`](https://github.com/kidonng/daisyui/blob/master/build.ts), which honestly doesn't do much.

**Comment by gotjoshua** [comment]
If you go to auto generated, i guess it makes sense to match the version tags from daisy, right?

Are you looking for help with any of the finishing touches?

**Comment by gotjoshua** [comment]
So I finally got around to trying out this implementation in my demo app.
Unfortunately, it doesn't work, because i am using [daisyui full.css from cdn](https://cdn.jsdelivr.net/npm/daisyui@2.24.0/dist/full.css)

I assume this is generated via [the build job in package.json](https://github.com/saadeghi/daisyui/blob/3127c8d87bd3cbd6152315fdc827f83f93d4125d/package.json#L69)

Can you imagine to include a build step that will also publish full.css in the format that fits with your unocss preset?

Actually what are the advantages to use the daisy uno preset over the cdn version?


note: I also opened [an issue to see if esbuild can do this](https://github.com/evanw/esbuild/issues/20) on the fly...

**Comment by kidonng** [comment]
> Unfortunately, it doesn't work, because i am using [daisyui full.css from cdn](https://cdn.jsdelivr.net/npm/daisyui@2.24.0/dist/full.css)

daisyUI's CDN version already have everything compiled, `unocss-preset-daisy` isn't designed to work with it. It's not an issue with this package either.

> Can you imagine to include a build step that will also publish full.css in the format that fits with your unocss preset?

Unless you are using UnoCSS without a build step (runtime version), I don't see the benefit of including a `full.css`, do you want to fetch and [compile the style](https://github.com//unocss/unocss/issues/1470#issuecomment-1228071668) yourself?

> Actually what are the advantages to use the daisy uno preset over the cdn version?

The CDN version doesn't allow customizing or selective import, while being 10x large compared to a full build using UnoCSS.

**Comment by gotjoshua** [comment]
> runtime version

I am using the runtime version... And although bigger, i have the opinion that the bloated size can be offset if many developers use the same CDN so that the libs get well cached in the wild.

Runtime compilation with transformer directives could be cool. Thanks for that link.

I am curious how the size of a full.css with all the @apply directives intact will compare to the daisy full.css that is shipping now.

Thanks for the exchange!

**Comment by kidonng** [comment]
> the bloated size can be offset if many developers use the same CDN so that the libs get well cached in the wild.

I don't know your target users, but most websites nowadays rarely use public CDNs for libraries other than the most popular ones (jQuery etc.) let alone niche ones like UnoCSS, so the potential cache benefits is neglectable.

> I am curious how the size of a full.css with all the `@apply` directives intact will compare to the daisy full.css that is shipping now.

I just added a full build (and [a minified one](https://cdn.jsdelivr.net/npm/@kidonng/daisyui@1.7.0/full.min.css)), the latter being 111KB and 22.1KB after gzipping.

**Comment by philippedasilva-orizone** [comment]
Hi @kidonng I forked this repo and made a quick sync up with daisyui 2.41.0 and when I tried to make a pull request, it seems I can't do so. Are you blocking pull requests on your side or am I doing something wrong?

I must admit I never really worked with repos including submodules so maybe the issue lies there? Don't know :)

Cheers

**Comment by kidonng** [comment]
I didn't block anything, I was just absent. I'm doing the sync work now.

**Comment by kidonng** [comment]
Good news! Since [`unocss-preset-daisy` 3.0.0](https://github.com/kidonng/unocss-preset-daisy/releases/tag/v3.0.0), you no longer need this package (`@kidonng/daisyui`). Instead, just install and upgrade the official `daisyui` package to keep up-to-date.
